version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_dw
    environment:
      POSTGRES_USER: user_f1
      POSTGRES_PASSWORD: password_f1
      POSTGRES_DB: f1_dw
    volumes:
      - ./data_layer/silver/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
